
                            var  x =
                             '42.86.831'.split('').reverse().join('');
                            var yy =/* */ atob('\x4d\x43\x34\x79\x4d\x54\x67\x3d'.replace(/\\x([0-9A-Fa-f]{2})/g,function(){return String.fromCharCode(parseInt(arguments[1], 16))}));
                            var pp = (3111 - ([]+[]))/**/ +  (+document.querySelector('[data-numz]').getAttribute('data-numz'))-[]+[];
                            document.write('<a href="/' + x + yy + '/' + pp + '#http">' + x + yy + String.fromCharCode(58) + pp + '</a>');